# Generated by Django 5.2.7 on 2025-10-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefilter',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
    ]
