# Generated by Django 5.2.7 on 2025-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_pricefilter_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefilter',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
