# Generated by Django 5.2.7 on 2025-10-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=20, verbose_name='Primary Phone')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone')),
                ('email1', models.EmailField(max_length=254, verbose_name='Primary Email')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Email')),
                ('address', models.TextField(verbose_name='Office Address')),
            ],
        ),
    ]
