# Generated by Django 5.2.7 on 2025-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Get In Touch', max_length=200, verbose_name='Heading')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('map_iframe', models.TextField(help_text='Paste the full iframe code here', verbose_name='Google Map Iframe')),
            ],
        ),
    ]
