# Generated by Django 5.2.1 on 2025-10-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_aboutsection_counter_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_1',
            field=models.ImageField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='image_2',
            field=models.ImageField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team'),
        ),
    ]
