# Generated by Django 5.2.1 on 2025-10-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_logo_alter_aboutsection_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text='Məs: Get up to 50% off Today Only!', max_length=255)),
                ('title', models.CharField(help_text='Məs: Winter Sale For Auto Parts', max_length=255)),
                ('highlight_text', models.CharField(blank=True, help_text='Məs: Auto Parts', max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
