# Generated by Django 5.2.1 on 2025-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_heroslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslider',
            name='highlight_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
