# Generated by Django 5.2.7 on 2025-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_heroslider_highlight_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AlterField(
            model_name='heroslider',
            name='image',
            field=models.ImageField(upload_to='sliders'),
        ),
    ]
