# Generated by Django 5.2.7 on 2025-10-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_brand_delete_logo_alter_heroslider_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
